-- 인원수에 따른 객실 조회
SELECT ROOM_TYPE, ROOM_RATES, ROOM_THUMBNAIL
FROM ROOM_TB
WHERE MAX_NUM >= 4;

-- 객실 타입에 따른 객실 가격 조회
SELECT ROOM_TYPE, ROOM_RATES
FROM ROOM_TB
WHERE ROOM_TYPE = 'SINGLE';

--  MEMBER_NM, JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
-- 예약 목록 조회
SELECT TO_CHAR(PAYMENT_DT, 'YYYY-MM-DD') PAYMENT_DT, MEMBER_NM, ROOM_NO, 
       TO_CHAR(CHECK_IN, 'YYYY-MM-DD') CHECK_IN,
       TO_CHAR(CHECK_OUT, 'YYYY-MM-DD') CHECK_OUT
FROM RESERVATION_CHECK
JOIN RESERVATION_REQ R USING(REQUEST_NO)
JOIN PAYMENT USING(PAYMENT_NO)
JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
WHERE RESERVATION_FL = 'Y';

SELECT OPTION_TYPE, OPTION_COUNT, REQUEST_NO
FROM RESERVATION_CHECK
JOIN OPTION_ORDER O USING(REQUEST_NO)
JOIN OPTION_TB P ON(O.OPTION_CD=P.OPTION_CD);

UPDATE OPTION_TB
SET OPTION_PRICE = 30000
WHERE OPTION_CD = 1;

SELECT * FROM OPTION_TB;

UPDATE ROOM_TB
SET ROOM_THUMBNAIL = '/resources/images/room/Single/single0.jpg'
WHERE ROOM_TYPE = 'SINGLE';

SELECT * FROM ROOM_TB;

SELECT * FROM RESERVATION_CHECK
JOIN RESERVATION_REQ USING(REQUEST_NO)
WHERE ROOM_TYPE = 'STANDARD';

SELECT * FROM RESERVATION_REQ
WHERE ROOM_TYPE = 'STANDARD';

SELECT * FROM MEMBER;

DROP TABLE MEMBER;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	       NUMBER		PRIMARY KEY,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	       VARCHAR2(100)		NOT NULL,
	"MEMBER_NM"	       VARCHAR2(40)		NOT NULL,
	"MEMBER_TEL"  	CHAR(11)		NOT NULL,
	"MEMBER_ADDR" 	VARCHAR2(500)		NULL,
	"MEMBER_BR"	       VARCHAR2(30)		NOT NULL,
	"ENROLL_DT"          DATE          DEFAULT SYSDATE NULL,
       "SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일( ID )';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."MEMBER_BR" IS '출생일';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '가입일';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '회원 탈퇴 여부';

CREATE SEQUENCE SEQ_MEMBER_NO;


SELECT PAYMENT_DT, MEMBER_NM, ROOM_NO, CHECK_IN, CHECK_OUT
FROM RESERVATION R
JOIN PAYMENT USING(REQUEST_NO)
JOIN MEMBER M ON(R.MEMBER_NO=M.MEMBER_NO);

SELECT MEMBER_NM, MEMBER_EMAIL
FROM MEMBER
WHERE MEMBER_NO = 1;

SELECT MEMBER_NM, OPTION_TYPE, OPTION_COUNT
FROM OPTION_ORDER
JOIN OPTION_TB USING(OPTION_CD)
JOIN RESERVATION R USING(REQUEST_NO)
JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
WHERE REQUEST_NO = 'OR202206120128460';

-- 결제 방법(JS에서 처리), 결제시간, 객실 비용, 결제 금액
SELECT PAYTYPE, TO_CHAR(PAYMENT_DT, 'YYYY-MM-DD HH:MI:SS') PAYMENT_DT, ROOM_RATES, PAYMENT_AMOUNT
FROM PAYMENT
JOIN RESERVATION R USING(REQUEST_NO)
JOIN ROOM_TB T ON(R.ROOM_TYPE = T.ROOM_TYPE);
-- WHERE REQUEST_NO = ?

