-- 인원수에 따른 객실 조회
SELECT ROOM_TYPE, ROOM_RATES, ROOM_THUMBNAIL
FROM ROOM_TB
WHERE MAX_NUM >= 4;

-- 객실 타입에 따른 객실 가격 조회
SELECT ROOM_TYPE, ROOM_RATES
FROM ROOM_TB
WHERE ROOM_TYPE = 'SINGLE';

--  MEMBER_NM, JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
-- 예약 목록 조회
SELECT TO_CHAR(PAYMENT_DT, 'YYYY-MM-DD') PAYMENT_DT, MEMBER_NM, ROOM_NO, 
       TO_CHAR(CHECK_IN, 'YYYY-MM-DD') CHECK_IN,
       TO_CHAR(CHECK_OUT, 'YYYY-MM-DD') CHECK_OUT
FROM RESERVATION_CHECK
JOIN RESERVATION_REQ R USING(REQUEST_NO)
JOIN PAYMENT USING(PAYMENT_NO)
JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
WHERE RESERVATION_FL = 'Y';




UPDATE ROOM_TB
SET ROOM_THUMBNAIL = '/resources/images/room/Single/single0.jpg'
WHERE ROOM_TYPE = 'SINGLE';

SELECT * FROM ROOM_TB;

SELECT * FROM RESERVATION_CHECK
JOIN RESERVATION_REQ USING(REQUEST_NO)
WHERE ROOM_TYPE = 'STANDARD';

SELECT * FROM RESERVATION_REQ
WHERE ROOM_TYPE = 'STANDARD';