CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(40)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(12)		NOT NULL,
	"BIRTH_DAY"	DATE		NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NULL,
	"REQUEST"	VARCHAR2(4000)		NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBERSHIP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일( ID )';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."BIRTH_DAY" IS '출생일';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '남 M / 여 W';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."REQUEST" IS '고객 요청 사항';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '회원 탈퇴 여부';

COMMENT ON COLUMN "MEMBER"."MEMBERSHIP_NO" IS '멤버십 번호';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);



CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user01@kh.or.kr','유저일','pass01','01012345678',
                        NULL,'W','서울시 중구 남대문로 120','고객요청사항',DEFAULT,'11');


   

COMMIT;
ROLLBACK;


SELECT *FROM MEMBER;

SELECT MEMBER_NO,MEMBER_EMAIL,MEMBER_NM,
TO_CHAR(BIRTH_DAY,'YYYY-MM-DD') AS BIRTH_DAY,
GENDER,ADDRESS,REQUEST,MEMBERSHIP_NO
FROM MEMBER
WHERE MEMBER_EMAIL='user01@kh.or.kr'
AND MEMBER_PW='pass01'
AND SECESSION_FL='N';

UPDATE MEMBER SET
MEMBER_PW = 'aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==';

UPDATE MEMBER SET
ADDRESS ='04540,,서울시 중구 남대문로 120,,2층 A강의장';


SELECT * FROM MEMBER;

SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user05@kh.or.kr','pass01!','유정오','01011112222','04540,,서울시 중구 남대문로 120,,2층 A강의장', '1994/01/01',
							DEFAULT,'N');


UPDATE MEMBER SET
MEMBER_PW ='aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg=='
WHERE MEMBER_NO=18;

SELECT MEMBER_NO,MEMBER_EMAIL,MEMBER_NM,MEMBER_TEL,
		MEMBER_BR,MEMBER_ADDR
		FROM MEMBER
		WHERE MEMBER_EMAIL='user05@kh.or.kr'
		AND MEMBER_PW='pass01!'
		AND SECESSION_FL='N';

--회원 탈퇴 
UPDATE MEMBER SET
   		SECESSION_FL='Y'
   		WHERE MEMBER_NO=19
   		AND MEMBER_PW='pass01!';

UPDATE MEMBER SET
   		SECESSION_FL='N'
   		WHERE MEMBER_NO=18
   		AND MEMBER_PW='aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==';


SELECT * FROM MEMBER;



UPDATE MEMBER SET
   		SECESSION_FL='N'
   		WHERE MEMBER_NO=18
   		AND MEMBER_PW='aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==';
